BoardConfig: convert partition sizes to Decimal
The Android build system requires that partition sizes are in decimal format

Fix for error:
ValueError: invalid literal for int() with base 10: '0x36e4f5b000'
ValueError: invalid literal for int() with base 10: '0x360000000'
ValueError: invalid literal for int() with base 10: '0x340c00000'
ValueError: invalid literal for int() with base 10: '0x1afc00000'

Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>